version: "3.8"

services:
  qdrant:
    environment:
      - QDRANT__DEBUG=${QDRANT_DEBUG}
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
      - QDRANT__TELEMETRY_DISABLED=true
      - QDRANT__STORAGE__STORAGE_PATH=./storage
    image: qdrant/qdrant:v1.4.0
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: {}
