stages:
  - Test
  - Build
  - Report

variables:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  PROJECT_SLUG: connect
  SENTRY_PROJECT_NAME: connect-backend
  VERSION_BEFORE_REF: ${CI_COMMIT_BEFORE_SHA}
  VERSION_REF: ${CI_COMMIT_SHA}

.staging:
  rules: &staging-rules
    - &pipeline-push-rule
      if: $CI_PIPELINE_SOURCE != "push"
      when: never
    - &staging-rule
      if: $CI_COMMIT_BRANCH == "main"
      variables:
        ENV_SLUG: stage
        STACK_SLUG: main
  environment:
    name: staging
    url: https://stage.connect.unich.it

.production:
  rules: &production-rules
    - <<: *pipeline-push-rule
    - &production-rule
      if: $CI_COMMIT_TAG
      variables:
        ENV_SLUG: prod
        STACK_SLUG: main
  environment:
    name: production
    url: https://connect.unich.it

.sentry:
  stage: .pre
  image: docker:20
  services:
    - docker:20-dind
  script:
    - >
      docker run --rm
      -v ${PWD}:${PWD}
      -w ${PWD}
      -e CI_ENVIRONMENT_NAME
      -e PROJECT_DIR=${CI_PROJECT_DIR}
      -e PROJECT_SLUG
      -e RELEASE_END
      -e RELEASE_START
      -e SENTRY_AUTH_TOKEN
      -e SENTRY_DSN
      -e SENTRY_ORG
      -e SENTRY_PROJECT_NAME
      -e SENTRY_URL
      -e VERSION_REF
      --entrypoint=""
      getsentry/sentry-cli:latest ./scripts/ci_sentry.sh ${SENTRY_CMD}

.sentry_release:
  extends:
    - .sentry
  variables:
    SENTRY_CMD: release
  before_script:
    - RELEASE_START=$(date +%s)

sentry_release_staging:
  extends:
    - .staging
    - .sentry_release
  rules:
    - &sentry-rule
      if: $SENTRY_ENABLED != "true"
      when: never
    - *staging-rules

sentry_release_production:
  extends:
    - .production
    - .sentry_release
  rules:
    - <<: *sentry-rule
    - *production-rules

test:
  stage: Test
  image: docker:20
  services:
    - docker:20-dind
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  variables:
    BACKEND_CONTAINER_NAME: "${CI_PROJECT_PATH_SLUG}-${CI_JOB_NAME}-${CI_JOB_ID}_backend"
    BACKEND_BUILD_TARGET: "test"
    BACKEND_IMAGE_NAME: "gitlabci_connect_backend"
    BACKEND_IMAGE_TAG: "${CI_JOB_NAME}-${CI_JOB_ID}"
    COMPOSE_PROJECT_NAME: "${CI_PROJECT_PATH_SLUG}-${CI_JOB_NAME}-${CI_JOB_ID}"
  script:
    - docker-compose build
    - docker-compose run --name ${BACKEND_CONTAINER_NAME} backend
    - docker cp ${BACKEND_CONTAINER_NAME}:/app/htmlcov htmlcov
  after_script:
    - docker-compose down -v
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    expire_in: 1 day
    paths:
      - htmlcov
    when: always

pages:
  stage: Report
  image: busybox
  needs: ["test"]
  rules:
    - <<: *pipeline-push-rule
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - mkdir public
    - mv htmlcov public/htmlcov
  artifacts:
    paths:
      - public

.build:
  stage: Build
  image: docker:20
  services:
    - docker:20-dind
  before_script:
    - export DOCKER_CONFIG=${PWD}/.dockerconfig
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:${VERSION_REF} --target remote --pull .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${VERSION_REF}
  after_script:
    - docker logout ${CI_REGISTRY}

build_staging:
  extends:
    - .staging
    - .build
  needs:
    - job: test

build_production:
  extends:
    - .production
    - .build
  needs:
    - job: test
