version: "3.8"

services:
  consumer:
    environment:
      - INTERNAL_BACKEND_URL=${INTERNAL_BACKEND_URL:-http://provider:8000}
      - NEXT_PUBLIC_PROJECT_URL=${NEXT_PUBLIC_PROJECT_URL:-https://localhost:8443}
      - REACT_ENVIRONMENT=${REACT_ENVIRONMENT:-development}
