accessLog: {}

api:
  insecure: false
  dashboard: false
  debug: false

certificatesResolvers:
  le-ssl:
    acme:
      storage: /letsencrypt/acme.json
      tlsChallenge: true
      httpChallenge:
        entryPoint: websecure

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

log:
  level: INFO

ping: true

providers:
  docker:
    network: default
    exposedByDefault: false
  file:
    filename: /traefik/conf/remote/dynamic.yaml
