version: "3.8"

services:
  backend:
    build:
      args:
        USER: ${USER:-appuser}
      context: ./backend
      target: ${BACKEND_BUILD_TARGET:-local}
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    environment:
      - DJANGO_QDRANT_URL=${QDRANT_URL}
      - DJANGO_QDRANT_API_KEY=${QDRANT_API_KEY}
    volumes:
      - ./backend:/app
      - .cache/pybliometrics:/home/${USER:-appuser}/.cache/pybliometrics/

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/local.Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app

  traefik:
    command:
      - "--configFile=/traefik/conf/local/static.yaml"
    ports:
      - "${LOCAL_HTTPS_PORT:-8443}:8443"
      - "${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
