version: "3.8"

services:
  backend:
    build:
      args:
        USER: ${USER:-appuser}
      context: ./backend
      target: ${BACKEND_BUILD_TARGET:-local}
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/local.Dockerfile
    volumes:
      - ./frontend:/app

  traefik:
    command:
      - "--configFile=/traefik/conf/local/static.yaml"
    ports:
      - "${LOCAL_HTTPS_PORT:-8443}:8443"
      - "${TRAEFIK_DASHBOARD_PORT:-8080}:8080"

  postgres:
    environment:
      - POSTGRES_DB=connect
      - POSTGRES_INITDB_ARGS=--no-sync
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 30
    image: postgres:15-bookworm
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
